# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'Pippin' do

  pod 'BonMot'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'KeyboardHelper', '~> 1.0'
  pod 'TTTAttributedLabel'
  pod 'lottie-ios'
  pod 'Shimmer'

  target 'PippinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
